// チューナー一覧
// numは通し番号
// bonはBonDriver_Spinel_PT3-**.dllの**部分
var tunerList = [
	{'num':	1,	'bon':	'T0'},
	{'num':	2,	'bon':	'T1'},
	{'num':	3,	'bon':	'T2'},
	{'num':	4,	'bon':	'T3'},
	{'num':	5,	'bon':	'S0'},
	{'num':	6,	'bon':	'S1'},
	{'num':	7,	'bon':	'S2'},
	{'num':	8,	'bon':	'S3'}
];

// サービスID一覧
var serviceList = [
	{'id':	3088,	'type':	'TS',	'name':	'東海テレビ'},
	{'id':	3080,	'type':	'TS',	'name':	'ＮＨＫＥテレ名古屋'},
	{'id':	33792,	'type':	'TS',	'name':	'ＮＨＫ総合・名古屋'},
	{'id':	3112,	'type':	'TS',	'name':	'中京テレビ'},
	{'id':	3096,	'type':	'TS',	'name':	'ＣＢＣテレビ'},
	{'id':	3104,	'type':	'TS',	'name':	'メ～テレ'},
	{'id':	33840,	'type':	'TS',	'name':	'テレビ愛知'},
	{'id':	1024,	'type':	'TS',	'name':	'ＮＨＫ総合・東京'},
	{'id':	1032,	'type':	'TS',	'name':	'ＮＨＫＥテレ東京'},
	{'id':	24632,	'type':	'TS',	'name':	'ｔｖｋ'},
	{'id':	1040,	'type':	'TS',	'name':	'日テレ'},
	{'id':	1064,	'type':	'TS',	'name':	'テレビ朝日'},
	{'id':	1048,	'type':	'TS',	'name':	'ＴＢＳ'},
	{'id':	1072,	'type':	'TS',	'name':	'テレビ東京'},
	{'id':	1056,	'type':	'TS',	'name':	'フジテレビ'},
	{'id':	23608,	'type':	'TS',	'name':	'ＴＯＫＹＯ ＭＸ１'},
	{'id':	23610,	'type':	'TS',	'name':	'ＴＯＫＹＯ ＭＸ２'},
	{'id':	24680,	'type':	'TS',	'name':	'イッツコムチャンネル１'},
	{'id':	24681,	'type':	'TS',	'name':	'イッツコムチャンネル２'},
	{'id':	24696,	'type':	'TS',	'name':	'イッツコムチャンネル３'},
	{'id':	24697,	'type':	'TS',	'name':	'イッツコムチャンネル４'},
	{'id':	1088,	'type':	'TS',	'name':	'放送大学１'},
	{'id':	1089,	'type':	'TS',	'name':	'放送大学２'},
	{'id':	1090,	'type':	'TS',	'name':	'放送大学３'},
	{'id':	101,	'type':	'BS',	'name':	'ＮＨＫＢＳ１'},
	{'id':	103,	'type':	'BS',	'name':	'ＮＨＫＢＳプレミアム'},
	{'id':	141,	'type':	'BS',	'name':	'ＢＳ日テレ'},
	{'id':	151,	'type':	'BS',	'name':	'ＢＳ朝日１'},
	{'id':	161,	'type':	'BS',	'name':	'ＢＳ－ＴＢＳ'},
	{'id':	171,	'type':	'BS',	'name':	'ＢＳジャパン'},
	{'id':	181,	'type':	'BS',	'name':	'ＢＳフジ・１８１'},
	{'id':	191,	'type':	'BS',	'name':	'ＷＯＷＯＷプライム'},
	{'id':	192,	'type':	'BS',	'name':	'ＷＯＷＯＷライブ'},
	{'id':	193,	'type':	'BS',	'name':	'ＷＯＷＯＷシネマ'},
	{'id':	200,	'type':	'BS',	'name':	'スターチャンネル１'},
	{'id':	201,	'type':	'BS',	'name':	'スターチャンネル２'},
	{'id':	202,	'type':	'BS',	'name':	'スターチャンネル３'},
	{'id':	211,	'type':	'BS',	'name':	'ＢＳ１１イレブン'},
	{'id':	222,	'type':	'BS',	'name':	'ＢＳ１２トゥエルビ'},
	{'id':	231,	'type':	'BS',	'name':	'放送大学ＢＳ１'},
	{'id':	232,	'type':	'BS',	'name':	'放送大学ＢＳ２'},
	{'id':	233,	'type':	'BS',	'name':	'放送大学ＢＳ３'},
	{'id':	234,	'type':	'BS',	'name':	'グリーンチャンネル'},
	{'id':	236,	'type':	'BS',	'name':	'ＢＳアニマックス'},
	{'id':	238,	'type':	'BS',	'name':	'ＦＯＸスポーツエンタ'},
	{'id':	241,	'type':	'BS',	'name':	'ＢＳスカパー！'},
	{'id':	242,	'type':	'BS',	'name':	'Ｊ ＳＰＯＲＴＳ １'},
	{'id':	243,	'type':	'BS',	'name':	'Ｊ ＳＰＯＲＴＳ ２'},
	{'id':	244,	'type':	'BS',	'name':	'Ｊ ＳＰＯＲＴＳ ３'},
	{'id':	245,	'type':	'BS',	'name':	'Ｊ ＳＰＯＲＴＳ ４'},
	{'id':	251,	'type':	'BS',	'name':	'ＢＳ釣りビジョン'},
	{'id':	252,	'type':	'BS',	'name':	'イマジカＢＳ・映画'},
	{'id':	255,	'type':	'BS',	'name':	'日本映画専門チャンネル'},
	{'id':	256,	'type':	'BS',	'name':	'ディズニー・チャンネル'},
	{'id':	258,	'type':	'BS',	'name':	'ディーライフ'},
	{'id':	531,	'type':	'BS',	'name':	'放送大学ラジオ'},
	{'id':	791,	'type':	'BS',	'name':	'ご案内チャンネル'},
	{'id':	55,		'type':	'CS',	'name':	'ショップチャンネル'},
	{'id':	100,	'type':	'CS',	'name':	'スカパー！プロモ'},
	/*{'id':	161,	'type':	'CS',	'name':	'ＱＶＣ'},*/
	{'id':	218,	'type':	'CS',	'name':	'東映チャンネル'},
	{'id':	219,	'type':	'CS',	'name':	'衛星劇場'},
	{'id':	223,	'type':	'CS',	'name':	'映画・ｃｈＮＥＣＯ'},
	{'id':	227,	'type':	'CS',	'name':	'ザ・シネマ'},
	{'id':	240,	'type':	'CS',	'name':	'ムービープラスＨＤ'},
	{'id':	250,	'type':	'CS',	'name':	'スカイＡ'},
	{'id':	254,	'type':	'CS',	'name':	'ＧＡＯＲＡ'},
	{'id':	257,	'type':	'CS',	'name':	'日テレジータス'},
	{'id':	262,	'type':	'CS',	'name':	'ゴルフネットＨＤ'},
	{'id':	290,	'type':	'CS',	'name':	'ＳＫＹ　ＳＴＡＧＥ'},
	{'id':	292,	'type':	'CS',	'name':	'時代劇専門ｃｈＨＤ'},
	{'id':	293,	'type':	'CS',	'name':	'ファミリー劇場ＨＤ'},
	{'id':	294,	'type':	'CS',	'name':	'ホームドラマＣＨ'},
	{'id':	295,	'type':	'CS',	'name':	'ＭＯＮＤＯ　ＴＶ'},
	{'id':	296,	'type':	'CS',	'name':	'ＴＢＳチャンネル１'},
	{'id':	297,	'type':	'CS',	'name':	'ＴＢＳチャンネル２'},
	{'id':	298,	'type':	'CS',	'name':	'テレ朝チャンネル１'},
	{'id':	299,	'type':	'CS',	'name':	'テレ朝チャンネル２'},
	{'id':	300,	'type':	'CS',	'name':	'日テレプラス'},
	{'id':	305,	'type':	'CS',	'name':	'銀河◆歴ドラ・サスペ'},
	{'id':	307,	'type':	'CS',	'name':	'フジテレビＯＮＥ'},
	{'id':	308,	'type':	'CS',	'name':	'フジテレビＴＷＯ'},
	{'id':	309,	'type':	'CS',	'name':	'フジテレビＮＥＸＴ'},
	{'id':	310,	'type':	'CS',	'name':	'スーパー！ドラマＨＤ'},
	{'id':	311,	'type':	'CS',	'name':	'ＡＸＮ　海外ドラマ'},
	{'id':	312,	'type':	'CS',	'name':	'ＦＯＸ'},
	{'id':	314,	'type':	'CS',	'name':	'女性ｃｈ／ＬａＬａ'},
	{'id':	316,	'type':	'CS',	'name':	'ＡＸＮミステリー'},
	{'id':	321,	'type':	'CS',	'name':	'スペシャプラス'},
	{'id':	322,	'type':	'CS',	'name':	'スペースシャワーＴＶ'},
	{'id':	323,	'type':	'CS',	'name':	'ＭＴＶ　ＨＤ'},
	{'id':	325,	'type':	'CS',	'name':	'エムオン！ＨＤ'},
	{'id':	326,	'type':	'CS',	'name':	'ミュージック・エア'},
	{'id':	329,	'type':	'CS',	'name':	'歌謡ポップス'},
	{'id':	330,	'type':	'CS',	'name':	'キッズステーション'},
	{'id':	331,	'type':	'CS',	'name':	'カートゥーン'},
	{'id':	333,	'type':	'CS',	'name':	'ＡＴ－Ｘ'},
	{'id':	339,	'type':	'CS',	'name':	'ディズニージュニア'},
	{'id':	340,	'type':	'CS',	'name':	'ディスカバリー'},
	{'id':	341,	'type':	'CS',	'name':	'アニマルプラネット'},
	{'id':	342,	'type':	'CS',	'name':	'ヒストリーチャンネル'},
	{'id':	343,	'type':	'CS',	'name':	'ナショジオチャンネル'},
	{'id':	349,	'type':	'CS',	'name':	'日テレＮＥＷＳ２４'},
	{'id':	351,	'type':	'CS',	'name':	'ＴＢＳニュースバード'},
	{'id':	353,	'type':	'CS',	'name':	'ＢＢＣワールド'},
	{'id':	354,	'type':	'CS',	'name':	'ＣＮＮｊ'},
	{'id':	363,	'type':	'CS',	'name':	'囲碁・将棋チャンネル'},
	{'id':	800,	'type':	'CS',	'name':	'スカチャン０'},
	{'id':	801,	'type':	'CS',	'name':	'スカチャン１'},
	{'id':	802,	'type':	'CS',	'name':	'スカチャン２'},
	{'id':	805,	'type':	'CS',	'name':	'スカチャン３'}
];